/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/8.0.1/samples
 */

plugins {
    kotlin("jvm") version "1.8.0"
    application
    id("com.github.johnrengelman.shadow") version "7.1.2"
    id("antlr")
}

group = "community.rto.ginger"
version = "0.0.1"

repositories {
    mavenCentral()
}


dependencies {
    antlr("org.antlr:antlr4:4.11.1")

    implementation("com.yuvalshavit:antlr-denter:1.1")
    implementation("com.github.ajalt.clikt:clikt:3.5.0")

    testImplementation(kotlin("test"))
}

application {
    mainClass.set("community.rto.ginger.rabbit.MainKt")
}

tasks.test {
    useJUnitPlatform()
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions.jvmTarget = "11"
}

tasks.compileJava {
    dependsOn(tasks.generateGrammarSource)
}

tasks.compileKotlin {
    dependsOn(tasks.generateGrammarSource)
}

tasks.generateGrammarSource {
    maxHeapSize = "128m"
    val path = file("$buildDir/generated-src/")
    val fullPath = path.resolve("antlr/main/community/rto/ginger/rabbit/antlr")
    doFirst {
        fullPath.mkdirs()
    }
    arguments = arguments + listOf(
        "-lib", fullPath.absoluteFile.toString(),
        "-visitor",
        "-no-listener",
        "-encoding", "UTF-8",
        "-package", "community.rto.ginger.rabbit.antlr"
    )
    outputDirectory = fullPath
}
